#!/bin/bash -e
#
# selrc
#
# This iscript is traditionally executed at the end of each multiuser
# runlevel, however in WSL there is no SysVInit or systemd by default.
# This incarnation is launched via /etc/wsl.conf:
#
#   [boot]
#   command="/etc/selrc"
#

# Fixup hosts
if [[ -n $WSL_DISTRO_NAME ]]; then
    echo $WSL_DISTRO_NAME >/etc/hostname
    hostname -F /etc/hostname
fi
sed -i "s/^\(127.0.1.1[[:space:]]*\).*$/\1 $WSL_DISTRO_NAME.\t$WSL_DISTRO_NAME/" /etc/hosts

# Run rc.local
if [[ -x /etc/rc.local ]]; then
    source /etc/rc.local
fi
