# users Role
---

- name: Create root .ssh directory
  # become: true
  file:
    path: /root/.ssh
    owner: root
    group: root
    state: directory
    mode: 0700

- name: Make root ssh keys
  openssh_keypair:
    path: /root/.ssh/id_ed25519
    type: ed25519
    comment: root@{{ ansible_hostname }}
    state: present

- name: Add sudo group
  group:
    name: "{{ sudo_group }}"
    state: present

- name: Add docker group
  group:
    name: "docker"
    state: present

# NOTE(mordred): We replace the main file rather than dropping a file in to
# /etc/sudoers.d to deal with divergent base sudoers files from our distros.
# We also want to change some default behavior (we want nopassword sudo, for
# instance).
- name: Setup sudoers file
  copy:
    dest: /etc/sudoers
    src: '{{ ansible_facts.os_family }}/sudoers'
    owner: root
    group: root
    mode: 0440

- name: Setup login.defs file
  copy:
    dest: /etc/login.defs
    src: '{{ ansible_facts.os_family }}/login.defs'
    owner: root
    group: root
    mode: 0644

- name: Delete old users
  loop: "{{ disabled_users }}"
  user:
    name: "{{ item }}"
    state: absent
    remove: yes

- name: Add groups
  loop: "{{ base_users + extra_users }}"
  group:
    name: "{{ item }}"
    state: present
    gid: "{{ all_users[item].gid|default(omit) }}"
  when:
    - item in all_users
    - "'gid' in all_users[item]"

- name: Add users
  loop: "{{ base_users + extra_users }}"
  user:
    name: "{{ item }}"
    state: present
    uid: "{{ all_users[item].uid }}"
    group: "{{ item }}"
    comment: "{{ all_users[item].comment }}"
    groups: "{{ sudo_group }}"
    shell: /bin/bash
  when:
    - item in all_users
    - "'uid' in all_users[item]"

- name: Add ssh keys to users
  loop: "{{ base_users + extra_users }}"
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ all_users[item].key }}"
    exclusive: yes
  when:
    - item in all_users
    - "'key' in all_users[item]"

- name: Make ssh keys for users
  loop: "{{ base_users + extra_users }}"
  openssh_keypair:
    path: "/home/{{ item }}/.ssh/id_ed25519"
    owner: "{{ item }}"
    group: "{{ item }}"
    type: ed25519
    comment: "{{ item }}@{{ ansible_hostname }}"
    state: present
  when:
    - item in all_users
